---
apiVersion: "rocketmq.shopiz.io/v1alpha1"
kind: BrokerCluster
metadata:
  name: mybrokercluster
  namespace : rocketmq-operator
spec:
  brokerImage: yeehawmars/rocketmq-broker-k8s:4.9.3
  nameServers: "10.56.1.5:9878;10.56.1.19:9878"
  allMaster: false
  replicationMode: SYNC
  groupReplica: 2
  membersPerGroup: 2
  emptyDir: false
  storageClassName: cbs-csi-expand
