---
apiVersion: "rocketmq.szbaixin.io/v1alpha1"
kind: BrokerCluster
metadata:
  name: mybrokercluster
  namespace : rocketmq-operator
spec:
  brokerImage: yeehawmars/rocketmq-broker-k8s:4.9.3
  nameServers: 10.10.103.181:9876;10.10.101.98:9876
  allMaster: true
  replicationMode: SYNC
  groupReplica: 2
  membersPerGroup: 2
  storageClassName: demo-nfs-storage
