---
apiVersion: "rocketmq.shopiz.io/v1alpha1"
kind: BrokerCluster
metadata:
  name: mybrokercluster
  namespace : rocketmq-operator
spec:
  brokerImage: yeehawmars/rocketmq-broker-k8s:4.9.3
  nameServers: "10.55.1.7:9876;10.55.1.15:9876"
  allMaster: false
  replicationMode: SYNC
  groupReplica: 2
  membersPerGroup: 2
  emptyDir: true
  # storageClassName: tke-cfs
